# Generated by Django 6.1 on 2026-08-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(db_index=True, max_length=128)),
                ('model_number', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('product_category', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('product_sub_category', models.CharField(blank=True, default='', max_length=255)),
                ('collection_name', models.CharField(blank=True, default='', max_length=255)),
                ('color_collection', models.CharField(blank=True, default='', max_length=128)),
                ('product_color', models.CharField(blank=True, default='', max_length=128)),
                ('materials', models.TextField(blank=True, default='')),
                ('bullets', models.TextField(blank=True, default='')),
                ('set_includes', models.TextField(blank=True, default='')),
                ('product_weight', models.CharField(blank=True, default='', max_length=64)),
                ('product_dimensions', models.TextField(blank=True, default='')),
                ('assembly_required', models.CharField(blank=True, default='', max_length=32)),
                ('is_set', models.CharField(blank=True, default='', max_length=32)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=128)),
                ('item_cost', models.FloatField(blank=True, null=True)),
                ('map_price', models.FloatField(blank=True, null=True)),
                ('msrp', models.FloatField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, default='')),
                ('all_images', models.JSONField(blank=True, default=list)),
                ('product_url', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product_number'], name='products_pr_product_1e41d2_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['product_category'], name='products_pr_product_e369fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.CharField(default='User', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(db_index=True, default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_classified', 'Auto Classified'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('extracted_attributes', models.JSONField(blank=True, default=dict)),
                ('confidence_breakdown', models.JSONField(blank=True, default=dict)),
                ('image_status', models.CharField(choices=[('available', 'Available'), ('missing', 'Missing'), ('broken', 'Broken / Unreachable'), ('unchecked', 'Unchecked')], default='unchecked', max_length=32)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=128)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('error_log', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_products', to='taxonomy.taxonomycategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='products.product')),
            ],
            options={
                'ordering': ['-confidence_score'],
                'indexes': [models.Index(fields=['status'], name='products_cl_status_697294_idx'), models.Index(fields=['confidence_score'], name='products_cl_confide_137720_idx'), models.Index(fields=['image_status'], name='products_cl_image_s_807105_idx')],
            },
        ),
    ]
