# Generated by Django 6.0.4 on 2026-08-17 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('taxonomy', '0002_taxonomycategory_taxonomy_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='approved_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to='taxonomy.taxonomycategory'),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='classifier_version',
            field=models.CharField(blank=True, default='v1.2.0', max_length=32),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('auto_classified', 'Auto Classified'), ('human_approved', 'Human Approved'), ('human_overridden', 'Human Overridden'), ('rejected', 'Rejected')], db_index=True, default='auto_classified', max_length=32),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='taxonomy_version',
            field=models.CharField(blank=True, db_index=True, default='2026-02', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_products', to='taxonomy.taxonomycategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['review_decision'], name='products_cl_review__59c6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['taxonomy_version'], name='products_cl_taxonom_e3fa69_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
    ]
