# Generated by Django 6.0.4 on 2026-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='batch_type',
            field=models.CharField(blank=True, default='full', max_length=32),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='resumed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
