# Generated by Django 6.1 on 2026-08-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('handle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='taxonomy_ta_name_00d3c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttributeValue',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.taxonomyattribute')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['attribute', 'name'], name='taxonomy_ta_attribu_6a3167_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(db_index=True, max_length=500)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('is_leaf', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attributes', models.ManyToManyField(blank=True, related_name='categories', to='taxonomy.taxonomyattribute')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.taxonomycategory')),
            ],
            options={
                'verbose_name_plural': 'Taxonomy Categories',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['name'], name='taxonomy_ta_name_06666d_idx'), models.Index(fields=['full_name'], name='taxonomy_ta_full_na_024475_idx'), models.Index(fields=['level'], name='taxonomy_ta_level_c9712f_idx')],
            },
        ),
    ]
