# Generated by Django 6.0.4 on 2026-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomycategory',
            name='taxonomy_version',
            field=models.CharField(blank=True, db_index=True, default='2026-02', max_length=32),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['taxonomy_version'], name='taxonomy_ta_taxonom_35fe70_idx'),
        ),
    ]
